site_name: Handbook for Learning Data Science
site_url: https://gsdsaml.github.io/HandbookForLearningDatascience/
repo_url: https://github.com/GSDSAML/HandbookForLearningDatascience

theme:
  name: "material"
  logo: img/Logo/logo.png
  custom_dir: overrides
  palette:
    primary: indigo
  features:
    - navigation.expand
    - toc.follow

markdown_extensions:
  - attr_list
  - md_in_html

plugins:
  - search
  - section-index
  - literate-nav:
      nav_file: SUMMARY.md
      implicit_index: true
      