site_name: Handbook for Learning Data Science
site_url: https://gsdsaml.github.io/HandbookForLearningDatascience/
repo_url: https://github.com/GSDSAML/HandbookForLearningDatascience

theme:
  name: "material"
  logo: img/logo/logo.png
  custom_dir: overrides
  palette:
    primary: indigo
  features:
    - navigation.indexes
    - toc.follow

plugins:
  - search
  - section-index
  - literate-nav:
      nav_file: SUMMARY.md
      implicit_index: false
      