site_name: Handbook for Learning Data Science
site_url: https://gsdsaml.github.io/HandbookForLearningDatascience/
repo_url: https://github.com/GSDSAML/HandbookForLearningDatascience

theme:
  name: "material"
  logo: img/logo/logo.png
  custom_dir: overrides
  palette:
    primary: indigo
  features:
    - navigation.expand
    - toc.follow

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - footnotes
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  - tables

plugins:
  - search
  - section-index
  - literate-nav:
      nav_file: SUMMARY.md
      implicit_index: true

extra_javascript:
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - javascripts/tablesort.js
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js