site_name: Handbook for Learning Data Science
site_url: https://gsdsaml.github.io/HandbookForLearningDatascience/
repo_url: https://github.com/GSDSAML/HandbookForLearningDatascience
nav:
  - Home: index.md
theme:
  name: "material"
  logo: img/logo/logo.png
  custom_dir: overrides
  palette:
    primary: indigo